id: f4d2c52e-5bf9-9097-f70b-a25bb251e320
type: controller
interactions: []
annotations:
  - namespace: c4modeler
    name: position
    value:
      f83ad5ca-73e0-7400-cb2d-16ea2a552a72:
        x: 223.15112540192925
        y: 157.13826513750377
name: Product
description: Description for NewController
children:
  - id: 0b113139-cca2-afbc-54b4-594a0515fe0c
    type: operation
