id: 95ccb922-91f3-4696-b784-ccfa5599194e
name: ProjectContext
type: c4-project
description: This is a sample project configuration for C4 model generation.
children:
  - id: a238dbfc-8b36-448f-816d-8c08585d53a7
    type: person
  - id: 81216553-1ca6-4b8e-856a-15950873bd13
    type: software-system
